"""create rack table

Revision ID: a91fcd6e4605
Revises: eb68e7ae047f
Create Date: 2025-09-08 02:15:47.406118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91fcd6e4605'
down_revision: Union[str, Sequence[str], None] = 'eb68e7ae047f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('max_power_consumption', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rack_name'), 'rack', ['name'], unique=False)
    op.create_index(op.f('ix_rack_serial_number'), 'rack', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rack_serial_number'), table_name='rack')
    op.drop_index(op.f('ix_rack_name'), table_name='rack')
    op.drop_table('rack')
    # ### end Alembic commands ###
