"""Create database

Revision ID: bcf978355397
Revises: 
Create Date: 2025-09-09 23:19:15.382838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf978355397'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('max_power_consumption', sa.Integer(), nullable=False),
    sa.Column('total_power_conssumption', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_racks_name'), 'racks', ['name'], unique=False)
    op.create_index(op.f('ix_racks_serial_number'), 'racks', ['serial_number'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('power_consumption', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.Enum('SERVER', 'SWITCH', 'ROUTER', 'STORAGE', 'OTHER', name='devicetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_racks_serial_number'), table_name='racks')
    op.drop_index(op.f('ix_racks_name'), table_name='racks')
    op.drop_table('racks')
    # ### end Alembic commands ###
