"""create device table

Revision ID: eb68e7ae047f
Revises: 
Create Date: 2025-09-07 15:22:55.148128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb68e7ae047f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('power_consumption', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.Enum('SERVER', 'SWITCH', 'ROUTER', 'STORAGE', 'OTHER', name='devicetype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
